export const MERMAID_MODERN_FONT_FAMILY =
  'Inter, ui-sans-serif, system-ui, -apple-system, "Segoe UI", sans-serif';

export const MERMAID_MODERN_THEME_VARIABLES = {
  primaryColor: '#F8FAFC',
  primaryTextColor: '#0F172A',
  primaryBorderColor: '#94A3B8',
  lineColor: '#64748B',
  secondaryColor: '#E2E8F0',
  tertiaryColor: '#FFFFFF',
  edgeLabelBackground: '#FFFFFF',
  clusterBkg: '#F1F5F9',
  clusterBorder: '#CBD5E1',
  background: '#FFFFFF',
  mainBkg: '#F8FAFC',
  secondBkg: '#E2E8F0',
  tertiaryBkg: '#FFFFFF',
  nodeBorder: '#94A3B8',
  textColor: '#0F172A',
  titleColor: '#0F172A',
  actorBkg: '#F8FAFC',
  actorBorder: '#94A3B8',
  actorTextColor: '#0F172A',
  actorLineColor: '#64748B',
  signalColor: '#64748B',
  signalTextColor: '#0F172A',
  labelBoxBkgColor: '#FFFFFF',
  labelBoxBorderColor: '#CBD5E1',
  labelTextColor: '#0F172A',
  loopTextColor: '#0F172A',
  noteBkgColor: '#FFF7ED',
  noteTextColor: '#0F172A',
  noteBorderColor: '#FDBA74',
  activationBkgColor: '#E2E8F0',
  activationBorderColor: '#94A3B8',
  pie1: '#CBD5E1',
  pie2: '#BFDBFE',
  pie3: '#BBF7D0',
  pie4: '#FDE68A',
  pie5: '#FED7AA',
  pie6: '#FBCFE8',
  pie7: '#DDD6FE',
  pie8: '#BAE6FD',
  pie9: '#A7F3D0',
  pie10: '#FECACA',
  pie11: '#E5E7EB',
  pie12: '#C7D2FE',
  pieTitleTextColor: '#0F172A',
  pieSectionTextColor: '#0F172A',
  pieLegendTextColor: '#0F172A',
  pieStrokeColor: '#334155',
  pieOuterStrokeColor: '#CBD5E1',
} as const;
