name: Build Custom Image

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:
    inputs:
      build-type:
        description: 'Build Type (e.g. stable, canary)'
        default: 'stable'
        required: true
      app-version:
        description: 'App Version'
        default: '0.26.3'
        required: true
      git-short-hash:
        description: 'Image Tag Suffix (e.g. custom)'
        default: 'custom'
        required: true

permissions:
  contents: 'write'
  id-token: 'write'
  packages: 'write'

jobs:
  build-custom-image:
    name: Trigger Build Images
    uses: ./.github/workflows/build-images.yml
    secrets: inherit
    with:
      build-type: ${{ inputs.build-type || 'stable' }}
      app-version: ${{ inputs.app-version || '0.26.3' }}
      git-short-hash: ${{ inputs.git-short-hash || github.sha }}
